<a href="https://colab.research.google.com/github/AimjGuytidy/pytorch-on/blob/main/pytorch_mastery.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi


Fri Feb 24 01:44:55 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   69C    P0    29W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.1+cu116


## Introducton to Tensors

### Creating tensors

In [3]:
scalar = torch.tensor(3)
scalar

tensor(3)

In [4]:
# dimension of the create scalar
scalar.ndim

0

In [5]:
# get tensor as python item
scalar.item()

3

In [6]:
# vectors with torch
vector = torch.tensor([3,3])
vector

tensor([3, 3])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [10]:
# matrix
matrix = torch.tensor([[3,2],
                      [1,4]])
matrix

tensor([[3, 2],
        [1, 4]])

In [11]:
matrix.ndim

2

In [12]:
matrix.shape

torch.Size([2, 2])

In [15]:
matrix[0]

tensor([3, 2])

In [16]:
# tensor
tensor = torch.tensor([[[1,2,3],
                        [3,4,5],
                        [7,8,9]]])
tensor

tensor([[[1, 2, 3],
         [3, 4, 5],
         [7, 8, 9]]])

In [18]:
tensor.ndim

3

In [19]:
tensor.shape

torch.Size([1, 3, 3])

In [21]:
tensor[0,1]

tensor([3, 4, 5])

### Random tensors

In [22]:
# create a random tensor of size (3,4)
rand_tensor = torch.rand(3,4)
rand_tensor 

tensor([[0.5055, 0.5391, 0.4475, 0.9556],
        [0.8394, 0.8389, 0.9839, 0.6344],
        [0.3575, 0.0480, 0.9077, 0.6243]])

In [23]:
rand_tensor.ndim

2

In [24]:
rand_tensor.shape

torch.Size([3, 4])

In [25]:
# create a random tensor with similar shape to an image tensor
rand_image_size_tensor = torch.rand(size=(3,224,224))
rand_image_size_tensor.shape, rand_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [26]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
# create a tensor of all ones
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [28]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [32]:
# use torch.range()
one_ten = torch.arange(1,11,step = 4)
one_ten

tensor([1, 5, 9])

In [33]:
# creating tensors like
ten_zeros = torch.zeros_like(input = one_ten)
ten_zeros

tensor([0, 0, 0])

### Tensor datatypes

In [34]:
# float 32 tensor
float_tensor = torch.tensor([3.,4.],
                            dtype = None,
                            device = None,
                            requires_grad=False)
float_tensor

tensor([3., 4.])

In [35]:
float_tensor.dtype

torch.float32

In [36]:
float_16 = float_tensor.type(torch.float16)
float_16

tensor([3., 4.], dtype=torch.float16)

In [37]:
float_tensor * float_16

tensor([ 9., 16.])

In [38]:
float_tensor.device

device(type='cpu')